### Listar de produtos
GET https://localhost:7213/equipe/listar

### Buscar produtos
GET https://localhost:7213/equipe/buscar/1

### Cadastrar produto
POST https://localhost:7213/equipe/cadastrar
Content-Type: application/json

{
    "nome": "Booleanos"
}