### Listar de produtos
GET https://localhost:7213/tarefa/listar

### Buscar produtos
GET https://localhost:7213/tarefa/buscar/1

### Cadastrar produto
POST https://localhost:7213/tarefa/cadastrar
Content-Type: application/json

    {
        "titulo": "Fazer algo",
        "descricao": "Alguma coisa",
        "concluirEm": "2023-11-05"
    }

    // opcional cadastrar com usuario e equipe
    //    "usuarioId": 1,
    //    "equipeId": 1